#数据源配置
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/personalblog?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=CONVERT_TO_NULL
    username: root
    password: 1234
  data:
    redis:
      host: localhost
      port: 6379
#mybatis驼峰命名匹配
mybatis:
  configuration:
    map-underscore-to-camel-case: true

